### ISSUE TITLE
#f866cc1 Fchan instances article

### ISSUE THREAD

**Issue by trueauracoral** [KushBlazingJudah/website#1]
*I am sending this message through github because IRC and XMPP are hard to use, I hate discord. I only have matrix.*

The article for fchan instances isn't going to automatically update as instances get added right? Is it possible someone could host https://git.fchannel.org/fchannel-index.git/? 

Or, is there possibly some API to get all the fchan instances? I want to be able to check which ones are dead. The article is still useful though.

**Comment by trueauracoral** [comment]
I looked at the code of Fchannel-Index it's using the /following API thing and is trying to use fchan.xyz. So I tried that on the working instance https://usagi.reisen/. Looking at the json output I see a bunch of links to now dead fchan instances. So the /following API is not reliable because it can't figure out if an instance is dead. Also now fchan.xyz is dead so now there is no list of available instances. I believe there needs to be community (rapidly decreasing in size) that will maintain an instance list.

**Comment by KushBlazingJudah** [comment]
I have to manually add and delete instances, and a slightly modified fchannel-index program (which now points at usagi.reisen) is how I source the information for the listing. I'll publish my changes in <https://github.com/KushBlazingJudah/fchannel-index> later today, I just need to clean it up slightly.

> is there possibly some API to get all the fchan instances

There is no API, ActivityPub provides all of the information we need. Instances are simply crawled to find other instances through their `/following` and `/followers`. I planned on making a JSON file available some point in the near future just to say it's there.
Dead instances are still going to be in their followers and following list, they are not automatically removed; instance owners may remove dead instances but are not obliged to.
